### ISSUE TITLE
HOW

### ISSUE THREAD

**Issue by jiangzhangze** [jorgensd/adios4dolfinx#11]
I installed dolfinx0.6.0 by conda on Ubuntu20.04.How to install adios4dolfinx in my system

**Comment by jorgensd** [comment]
`python3 -m pip install git+ https://github.com/jorgensd/adios4dolfinx`
inside your conda environment. You might need to install pip with conda as well.

**Comment by jiangzhangze** [comment]
Hi @jorgensd ,thanks for your reply.It may be convenienced that add how to install it into [documntion](https://jsdokken.com/adios4dolfinx/README.html)?
