### ISSUE TITLE
small inconsistency in arguments order in user facing functions

### ISSUE THREAD

**Issue by francesco-ballarin** [jorgensd/adios4dolfinx#63]
Copying from the tests

```
adios4dolfinx.write_mesh(mesh, filename, "bp4")
adios4dolfinx.write_meshtags(filename, mesh, ft, "bp4")
adios4dolfinx.write_function(uh, filename, time=0.0)
```

In `write_mesh` and `write_function`, the object to be written comes first, and the filename afterwards.
In the recently added `write_meshtags`, the filename comes first and the mesh & object to be written afterwards.

Maybe it was on purpose: if so, feel free to close.
Maybe it wasn't on purpose, but with the (recent) release out there it's too late to go back: if so, feel free to close.

**Comment by jorgensd** [comment]
I would like to wait until we release 0.8.0 with changing the API;) 
But lets be consistent in write_meshtags.
