### ISSUE TITLE
Set default arguments for `engine` and `ghost_mode` in `read_mesh`

### ISSUE THREAD

**Issue by finsberg** [jorgensd/adios4dolfinx#69]
Perhaps a controversial topic to ask for defaults, but in my opinion it would be good to set default values for `engine` and `ghost_mode`. For example `engine`=`"BP4"` and `ghost_mode=dolfinx.mesh.GhostMode.shared_facet`.

**Comment by jorgensd** [comment]
I think it is fine, feel free to add a PR:)
