### ISSUE TITLE
ipyparallel missing in installation instructions

### ISSUE THREAD

**Issue by Chilipp** [jorgensd/adios4dolfinx#95]
hey @jorgensd! I am just reviewing your software as part of https://github.com/openjournals/joss-reviews/issues/6451 and I am trying to install it. The conda installation works well, but in your documentation you heavily make use of the [ipyparallel](https://ipyparallel.readthedocs.io/en/latest/) library, that is not mentioned in your installation instructions. this needs to be added

**Comment by jorgensd** [comment]
IPython parallel is listed under optional dependencies:
https://github.com/jorgensd/adios4dolfinx/blob/main/pyproject.toml#L13-L17
I've made a clarification in the installation instructions: https://github.com/jorgensd/adios4dolfinx/pull/96
Let me know if that is a sufficient clarification.

Please note that it is v0.8.0 of this software that is under review.
Unfortunately we do not have a conda release compatible with 0.8.0 yet (as DOLFINx hasn't had a 0.8.0 release, and the current version of the code relies on some interface changes in DOLFINx that I introduced).

Therefore, I would advice you to use `docker` for the time being, for instance with: 
` docker run -ti -v $(pwd):/root/shared -w /root/shared --rm ghcr.io/fenics/dolfinx/dolfinx:nightly`

**Comment by Chilipp** [comment]
@jorgensd unfortunately your fix in #96 did not solve the problem, as you did install `v0.7.3` in the instructions. this version however does not list `ipyparallel` in the [optional dependencies](https://github.com/jorgensd/adios4dolfinx/blob/v0.7.3/pyproject.toml) and as far as I understood, it's not the version we are supposed to review :wink: so please reopen this issue

**Comment by jorgensd** [comment]
I’m a bit uncertain as to what you would like me to specify? 
The version under review is 0.8 (which would be equivalent to the main branch, as i will make a new release (0.8.1) once the review is finalized).

Could you elaborate on what you think the current issue (with the main branch) of the software is?

**Comment by Chilipp** [comment]
ah, my apologies @jorgensd, I copied the installation instruction for the test setup from the conda section, and not from the docker section. In docker, you indeed referenced the `main` branch which is ok (see #97)
